# Generated by Django 3.2 on 2021-05-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='none', upload_to='images'),
            preserve_default=False,
        ),
    ]
